name: Python checks on snakepackage

on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  run-linters:
    name: Run test
    runs-on: windows-latest

    steps:
    - name: Run flake8
    - uses: actions/checkout@v3
    - uses: Irina13155/flake8-check-action@master
      with:
        flake8: true
        path: snakepackage
        repotoken: ${{ secrets.GITHUB_TOKEN }}
        maxlinelength: 100