name: Python checks on snakepackage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-linters:
    name: Run test
    runs-on: windows-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Checkout Git repository
      uses: actions/checkout@v3

    - name: Run flake8
      uses: py-actions/flake8@v2
      with:
        path: snakepackage
        max-line-length: 100
